# src/llm_handler.py
from groq import Groq
from typing import List, Dict, Any
import logging
from src.llm_fallback_handler import LLMFallbackHandler

class LLMHandler:
    def __init__(self, config):
        self.config = config
        self.logger = logging.getLogger(__name__)
        self.conversation_history = []

        # Initialize fallback handler (supports Groq + 3 fallbacks)
        try:
            self.fallback_handler = LLMFallbackHandler(config)
            self.client = None  # Will use fallback_handler instead
            self.logger.info("LLM Handler initialized with fallback support")
        except Exception as e:
            self.logger.error(f"Failed to initialize fallback handler: {e}")
            # Fallback to direct Groq if everything fails
            if not config.GROQ_API_KEY:
                self.logger.error("GROQ_API_KEY is not set. Please add your API key to the .env file.")
                self.client = None
                self.fallback_handler = None
            else:
                self.client = Groq(api_key=config.GROQ_API_KEY)
                self.fallback_handler = None
        
    def generate_response(self, query: str, context_docs: List[Dict[str, Any]],
                         conversation_history: List[str] = None) -> Dict[str, Any]:
        """Generate response using retrieved context"""

        # DEBUG: Log context docs received
        self.logger.info(f"🔍 LLM received {len(context_docs)} context docs")
        for i, doc in enumerate(context_docs[:3]):  # Log first 3
            self.logger.info(f"   Doc {i+1}: type={doc['metadata'].get('chunk_type')}, page={doc['metadata'].get('page_number')}")
            content_preview = doc['content'][:200].replace('\n', ' ')
            self.logger.info(f"   Content preview: {content_preview}...")

        # Prepare context from retrieved documents
        context_text = self._prepare_context(context_docs)

        # DEBUG: Log if image analysis is present in context
        if "📷" in context_text or "Visual Content" in context_text:
            self.logger.info("✅ IMAGE ANALYSIS DETECTED IN CONTEXT - LLM should see this!")
            # Log a snippet of the image analysis
            for line in context_text.split('\n'):
                if "📷" in line or "Visual Content" in line:
                    self.logger.info(f"   Image line: {line[:150]}")
        else:
            self.logger.warning("⚠️ NO IMAGE ANALYSIS IN CONTEXT - Images not reaching LLM!")

        # Build conversation context
        conversation_context = self._build_conversation_context(conversation_history)

        # Create prompt
        prompt = self._create_prompt(query, context_text, conversation_context)
        
        try:
            # Check if fallback handler is available
            if self.fallback_handler is None and self.client is None:
                error_message = "ERROR: No LLM provider is available. Please check your API keys in the .env file."
                self.logger.error(error_message)
                return {
                    'answer': error_message,
                    'sources_used': len(context_docs),
                    'context_types': list(set([doc['metadata']['chunk_type'] for doc in context_docs])),
                    'confidence': 0.0,
                    'error': True
                }

            # Use fallback handler if available (preferred)
            if self.fallback_handler:
                # Build conversation history for fallback handler
                conv_history = []
                if conversation_history:
                    conv_history = conversation_history

                # Determine max_tokens based on query type
                # Higher limits to ensure responses complete properly (esp. for regional languages)
                if any(keyword in query.lower() for keyword in ['summarize', 'summary', 'explain', 'describe', 'long', 'detail']):
                    max_tokens = 4000  # Generous limit for detailed explanations/summaries
                else:
                    max_tokens = 1500  # Sufficient for complete answers to direct questions

                # Use fallback handler with automatic provider cascade
                result = self.fallback_handler.query_text(
                    question=prompt,
                    conversation_history=conv_history,
                    system_prompt=self._get_system_prompt(),
                    max_tokens=max_tokens
                )

                if result['success']:
                    answer = result['answer']
                    self.logger.info(f"✅ Response generated by {result['provider']} ({result['model']})")
                else:
                    answer = result['answer']  # Will contain error message
                    self.logger.error(f"❌ All providers failed: {result.get('error', 'Unknown error')}")

            else:
                # Fallback to direct Groq (legacy mode)
                # Determine max_tokens based on query type
                # Higher limits to ensure responses complete properly (esp. for regional languages)
                if any(keyword in query.lower() for keyword in ['summarize', 'summary', 'explain', 'describe', 'detail']):
                    max_tokens = 4000  # Generous limit for detailed explanations/summaries
                else:
                    max_tokens = 1500  # Sufficient for complete answers to direct questions

                response = self.client.chat.completions.create(
                    model=self.config.LLM_MODEL,
                    messages=[
                        {"role": "system", "content": self._get_system_prompt()},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=0.4,  # Lower for more direct, factual responses
                    max_tokens=max_tokens,
                    top_p=1,
                    stream=False
                )
                answer = response.choices[0].message.content
                self.logger.info("✅ Response generated by Groq (direct mode)")
            
            # Update conversation history
            self.conversation_history.append(f"User: {query}")
            self.conversation_history.append(f"Assistant: {answer}")
            
            # Prepare sources for frontend
            sources = []
            for doc in context_docs[:3]: # Limit to top 3 relevant sources
                sources.append({
                    'page': doc['metadata'].get('page_number', '?'),
                    'document': doc['metadata'].get('document_name', 'Unknown'),
                    'text': doc['content'][:150] + "..." # Snippet
                })

            return {
                'answer': answer,
                'sources': sources, # structured sources for UI citations
                'sources_used': len(context_docs),
                'context_types': list(set([doc['metadata']['chunk_type'] for doc in context_docs])),
                'confidence': self._calculate_confidence(context_docs),
                'error': False
            }
            
        except Exception as e:
            self.logger.error(f"Error generating response: {e}")
            return {
                'answer': "I apologize, but I encountered an error while generating a response. Please try again.",
                'sources_used': 0,
                'context_types': [],
                'confidence': 0.0
            }
    
    def generate_summary(self, text: str) -> str:
        """Generate a summary of the provided text"""
        # Truncate text to fit in context (approx 15k chars ~ 3-4k tokens)
        truncated_text = text[:15000]
        
        prompt = f"""Summarize the following document content in a concise and structured manner (bullet points).
Focus on the main concepts, key takeaways, and any important conclusions.

CONTENT:
{truncated_text}

... [truncated] ...

SUMMARY:"""

        try:
            if self.fallback_handler:
                 result = self.fallback_handler.query_text(
                    question=prompt,
                    system_prompt="You are an expert synthesizer of information. Create clear, structured summaries.",
                    max_tokens=1500
                )
                 return result['answer'] if result['success'] else "Failed to generate summary."
            
            if not self.client:
                return "No LLM provider available."

            # Fallback to direct
            response = self.client.chat.completions.create(
                model=self.config.LLM_MODEL,
                messages=[
                    {"role": "system", "content": "You are an expert synthesizer of information. Create clear, structured summaries."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=1500
            )
            return response.choices[0].message.content
            
        except Exception as e:
            self.logger.error(f"Error generating summary: {e}")
            return "An error occurred while generating the summary."

    def generate_flashcards(self, text: str, num_cards: int = 5) -> List[Dict[str, str]]:
        """Generate flashcards from text"""
        import json
        import re

        # Truncate text to fit in context
        truncated_text = text[:15000]
        
        prompt = f"""Create {num_cards} high-quality flashcards based on the following content.
Format your response as a RAW JSON array of objects, where each object has:
- "front": The question or concept
- "back": The answer or definition
- "page_number": The page number (integer) where this information was found (extracted from the [Page X] markers in the text). If unsure, use null.

Do NOT use Markdown formatting (no ```json or ```). Just return the raw JSON array.

CONTENT:
{truncated_text}

... [truncated] ...

JSON RESPONSE:"""

        try:
            response_text = ""
            if self.fallback_handler:
                 result = self.fallback_handler.query_text(
                    question=prompt,
                    system_prompt="You are an educational tool generator. Output only valid JSON.",
                    max_tokens=2000
                )
                 if result['success']:
                     response_text = result['answer']
            
            if not response_text and self.client:
                response = self.client.chat.completions.create(
                    model=self.config.LLM_MODEL,
                    messages=[
                        {"role": "system", "content": "You are an educational tool generator. Output only valid JSON."},
                        {"role": "user", "content": prompt}
                    ],
                    max_tokens=2000
                )
                response_text = response.choices[0].message.content

            if not response_text:
                return []

            # Clean up response (remove markdown if present)
            clean_text = re.sub(r'```json\s*', '', response_text)
            clean_text = re.sub(r'```\s*', '', clean_text)
            clean_text = clean_text.strip()
            
            return json.loads(clean_text)
            
        except Exception as e:
            self.logger.error(f"Error generating flashcards: {e}")
            return []

    def generate_roadmap(self, text: str) -> str:
        """Generate a Mermaid.js roadmap/mindmap"""
        import re
        
        # Truncate text
        truncated_text = text[:15000]
        
        prompt = f"""Create a detailed and structured Mind Map for the following content using Mermaid.js syntax.
Use the 'mindmap' diagram type.
Start with `mindmap` and indentation.
Ensure the syntax is valid. Do not use special characters that might break Mermaid.

CONTENT:
{truncated_text}

... [truncated] ...

Example Output Format:
mindmap
  root((Main Topic))
    Subtopic 1
      Detail A
      Detail B
    Subtopic 2
      Detail C

MERMAID CODE (Raw only):"""

        try:
            response_text = ""
            if self.fallback_handler:
                 result = self.fallback_handler.query_text(
                    question=prompt,
                    system_prompt="You are a visual learning expert. Output only valid Mermaid.js code.",
                    max_tokens=1500
                )
                 if result['success']:
                     response_text = result['answer']
            
            if not response_text and self.client:
                response = self.client.chat.completions.create(
                    model=self.config.LLM_MODEL,
                    messages=[
                        {"role": "system", "content": "You are a visual learning expert. Output only valid Mermaid.js code."},
                        {"role": "user", "content": prompt}
                    ],
                    max_tokens=1500
                )
                response_text = response.choices[0].message.content

            if not response_text:
                return "graph TD\nError[Failed to generate roadmap]"

            # Clean up response (remove markdown)
            clean_text = re.sub(r'```mermaid\s*', '', response_text)
            clean_text = re.sub(r'```\s*', '', clean_text)
            clean_text = clean_text.strip()
            
            return clean_text
            
        except Exception as e:
            self.logger.error(f"Error generating roadmap: {e}")
            return "graph TD\nError[Error generating roadmap]"

    def _prepare_context(self, context_docs: List[Dict[str, Any]]) -> str:
        """Prepare context from retrieved documents with smart truncation"""
        context_parts = []
        # Reduced to fit within Groq's 6k TPM limit (leave 2k for prompt+response)
        max_context_tokens = 3000
        estimated_tokens = 0

        # Limit to top 3 most relevant docs to avoid token overflow
        docs_to_use = context_docs[:3]

        for i, doc in enumerate(docs_to_use, 1):
            content = doc['content']
            metadata = doc['metadata']

            # Estimate tokens (rough: 1 token ≈ 4 characters)
            content_tokens = len(content) // 4

            # If this chunk would exceed limit, truncate it
            if estimated_tokens + content_tokens > max_context_tokens:
                remaining_tokens = max_context_tokens - estimated_tokens
                if remaining_tokens > 100:  # Only include if we can fit meaningful content
                    content = content[:remaining_tokens * 4] + "... [truncated]"
                    content_tokens = remaining_tokens
                else:
                    break  # Stop adding more chunks

            # Minimal context formatting - just content and page
            context_part = f"""{content} [Page {metadata['page_number']}]

"""
            context_parts.append(context_part)
            estimated_tokens += content_tokens

            # Stop if we're approaching the limit
            if estimated_tokens >= max_context_tokens:
                break

        self.logger.info(f"📊 Context prepared: {estimated_tokens} estimated tokens from {len(context_parts)} docs")
        return "\n".join(context_parts)
    
    def _build_conversation_context(self, conversation_history: List[str]) -> str:
        """Build conversation context"""
        if not conversation_history:
            return ""
        
        return "CONVERSATION HISTORY:\n" + "\n".join(conversation_history[-6:])  # Last 3 exchanges
    
    def _create_prompt(self, query: str, context_text: str, conversation_context: str) -> str:
        """Create the complete prompt (optimized for transparency)"""
        prompt = f"""CONTEXT:
{context_text}

QUESTION: {query}

INSTRUCTIONS:
1. Answer the question using ONLY the provided CONTEXT above.
2. If the answer is found in the context, provide it directly and concisely.
3. If the answer is NOT found in the context, YOU MUST START YOUR RESPONSE WITH:
   "⚠️ **Note:** This information is not found in your uploaded document, so I am using my general knowledge to answer."
   Then provide the answer to the best of your ability.

4. Do NOT mention "the document" or "the context" in your answer unless necessary. Just state the facts.
"""
        return prompt

    def _get_system_prompt(self) -> str:
        """Get system prompt for the LLM"""
        return """You are a friendly and knowledgeable tutor. Answer questions naturally and directly.

RESPONSE MODES:
1. For GENERAL KNOWLEDGE questions: Use your knowledge to give accurate, helpful answers
2. For DOCUMENT-SPECIFIC questions: Answer strictly from the provided context

VISUAL CONTENT RULES (Roadmaps & Diagrams):
✅ You CAN generate visual diagrams using Mermaid.js.
- If user asks for a "roadmap", "mind map", "flowchart", or "diagram":
- Generate valid Mermaid.js code enclosed in a code block with the language identifier 'mermaid'.
- For Roadmaps/Mind Maps: Use `mindmap` or `graph TD` (flowchart).
- Keep diagrams clear and hierarchical.

Example:
```mermaid
graph TD
    A[Start] --> B{Is it working?}
    B -- Yes --> C[Great!]
    B -- No --> D[Fix it]
```

LANGUAGE RULES (CRITICAL - MUST FOLLOW):
⚠️ ALWAYS respect the user's language preference!
- If user says "in Hindi" or "हिंदी में" → Respond ONLY in Hindi (हिंदी script)
- If user says "in Kannada" or "ಕನ್ನಡದಲ್ಲಿ" → Respond ONLY in Kannada (ಕನ್ನಡ script)
- If user says "in English" → Respond ONLY in English
- If no language specified → Respond in English by default
- NEVER mix scripts or languages in your response
- Match the EXACT script of the requested language (Devanagari for Hindi, Kannada script for Kannada)

LANGUAGE EXAMPLES:
Q: "explain chemistry in Hindi"
A: रसायन विज्ञान पदार्थों की संरचना, गुण और परिवर्तन का अध्ययन है... (FULL response in Hindi)

Q: "explain chemistry in Kannada"
A: ರಸಾಯನಶಾಸ್ತ್ರವು ಪದಾರ್ಥಗಳ ರಚನೆ, ಗುಣಲಕ್ಷಣಗಳು ಮತ್ತು ಬದಲಾವಣೆಗಳ ಅಧ್ಯಯನವಾಗಿದೆ... (FULL response in Kannada)

STYLE RULES:
1. Give DIRECT answers - no meta-commentary
2. NEVER say "Document Excerpt X" or "it is mentioned that"
3. Answer like you're explaining to a friend
4. For document queries with no answer: "I cannot find this information in the uploaded document(s)."

LENGTH:
- "What is X?" → 2-4 sentences
- "Explain X" → 4-6 sentences maximum
- Keep answers CONCISE and CLEAR

FORBIDDEN PHRASES:
❌ "In the context above"
❌ "Document Excerpt X"
❌ "it is mentioned that"
❌ "according to the document"
❌ Any meta-commentary about sources or context

ALLOWED (Simple and Direct):
✅ Just answer naturally
✅ Include page numbers in parentheses if helpful: (Page 5)
✅ Use **bold** for key terms

EXAMPLES:

Q: "What are ketones?"
A: **Ketones** are organic compounds with a carbonyl group (C=O) bonded to two carbon atoms. They're important in organic chemistry and used in flavourings, plastics, and drugs (Page 71).

Q: "What are real numbers?"
A: **Real numbers** include all rational and irrational numbers that can be represented on a number line. Examples include integers like 3, fractions like 1/2, and irrational numbers like √2 and π (Page 1).

Q: "Why do we use chemistry?"
A: We use chemistry to create medicines for treating diseases, preserve food, develop cleaning products, and make materials like plastics and fabrics that we use daily (Page 165).

REMEMBER: Just answer directly! No analysis of what's in the context! ALWAYS respect language preferences!
"""
    
    def _calculate_confidence(self, context_docs: List[Dict[str, Any]]) -> float:
        """Calculate confidence score based on retrieved context"""
        if not context_docs:
            return 0.0
        
        # Base confidence on similarity scores and number of sources
        avg_score = sum([doc['score'] for doc in context_docs]) / len(context_docs)
        source_bonus = min(len(context_docs) / 5, 1.0)  # Bonus for multiple sources
        
        return min(avg_score * (1 + source_bonus * 0.2), 1.0)
    
    def clear_history(self):
        """Clear conversation history"""
        self.conversation_history = []


# ============================================================================
# Streaming Helper Function
# ============================================================================

def get_groq_streaming_response(prompt: str):
    """
    Get streaming response from Groq API
    Yields text chunks as they arrive

    Args:
        prompt: The prompt to send to LLM

    Yields:
        str: Text chunks from the LLM
    """
    import os
    from groq import Groq

    try:
        client = Groq(api_key=os.getenv('GROQ_API_KEY'))

        # Create streaming completion
        stream = client.chat.completions.create(
            model="llama-3.1-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": "You are a helpful assistant. Answer concisely and accurately based on the provided context."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            stream=True,
            temperature=0.7,
            max_tokens=1500
        )

        # Yield chunks as they arrive
        for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content:
                yield chunk.choices[0].delta.content

    except Exception as e:
        logging.error(f"Streaming error: {e}")
        # Fallback: Return error message
        yield f"Error: {str(e)}"
